services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db_training_center
    environment:
      POSTGRES_DB: training_center_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data_training_center:/var/lib/postgresql/data
    ports:
      - "5500:5432"
    networks:
      - shared-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: training_center_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/training_center_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    ports:
      - "8087:8080"
      - "9091:9090"
    volumes:
      - ./db/changelog:/src/main/resources/db/changelog
    networks:
      - kafka-net
      - shared-net
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data_training_center:

networks:
  kafka-net:
    driver: bridge
  shared-net:
    driver: bridge