services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: car_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data_non_auto2:/var/lib/postgresql/data
    ports:
      - "5499:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - shared-net

  app:
    build: .
    container_name: api_gateway_app
    ports:
      - "8087:8080"
      - "9091:9090"
      - "9092:"
    networks:
      - shared-net
    environment:
      GRPC_STORING_SERVICE_URL: storing_service:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5499/car_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      postgres_training_center:
        condition: service_healthy

volumes:
  postgres_data_training_center:

networks:
  shared-net:
    name: shared-net
    driver: bridge