services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_antiplag_file_storing
    environment:
      POSTGRES_DB: file_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data_antiplag_file_storing:/var/lib/postgresql/data
    ports:
      - "5501:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: storingServiceApp
    ports:
      - "7071:7070" # grpc
    networks:
      - shared-net
      - default
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_antiplag_file_storing:5432/file_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      GRPC_LISTENING_PORT: 7070
      FILE_STORING_SERVICE_PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data_antiplag_file_storing:

networks:
  shared-net:
    name: shared-net
    driver: bridge