services:
  app:
    build: .
    container_name: api_gateway_app
    ports:
      - "8080:8080" # server
    networks:
      - shared-net
    environment:
      GRPC_STORING_SERVICE_URL: storing_service_app:7071
      GRPC_ANALYSIS_SERVICE_URL: analysis_service_app:7072
      API_SERVICE_PORT: 8080

networks:
  shared-net:
    name: shared-net
    driver: bridge