services:
  app:
    build: .
    container_name: api_gateway_app
    ports:
      - "8080:8080" # server
    networks:
      - shared-net
    environment:
      GRPC_STORING_SERVICE_URL: storingServiceApp:7070
      GRPC_ANALYSIS_SERVICE_URL: analysisServiceApp:7070
      API_SERVICE_PORT: 8080

networks:
  shared-net:
    name: shared-net
    driver: bridge